name: namer_app
description: A Flutter project for generating random word pairs and marking favorites.

# Flutter environment version
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  web_socket_channel: ^2.3.0
  parallax: 1.0.3
  shimmer: ^2.0.0 # Para el shimmer loading effect
  # Dependencias necesarias para el proyecto
  english_words: ^4.0.0 # Para generar palabras aleatorias
  provider: ^6.0.5      # Para la gestión del estado
  rename: ^3.0.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.4.0

# Configuración para Flutter
flutter:
  uses-material-design: true

  # Configuración de assets y fuentes
  assets:
    - assets/fonts/
    - assets/loading.gif


  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/static/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/static/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/static/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/static/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
